# Generated by Django 3.0 on 2020-04-21 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Nome')),
                ('city', models.CharField(max_length=254, verbose_name='Cidade')),
                ('phonenumber', models.CharField(max_length=16, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Nome')),
                ('birthday', models.DateField(verbose_name='Data de Nascimento')),
                ('airways', models.CharField(choices=[('VM', 'Ventilação Mecânica'), ('AA', 'Ar Ambiente'), ('VNI', 'Ventilação não Invasiva')], default='AA', max_length=24, verbose_name='Vias Aéreas')),
                ('status', models.CharField(choices=[('S', 'Suspeito'), ('C', 'Confirmado'), ('D', 'Descartado')], default='S', max_length=10, verbose_name='Status COVID')),
                ('hospitalization_date', models.DateField(verbose_name='Data de Internação')),
                ('departure_date', models.DateField(verbose_name='Data de Saída')),
                ('cns', models.CharField(blank=True, default='', max_length=30, verbose_name='Carteira Nacional do SUS')),
                ('sisreg', models.CharField(blank=True, default='', max_length=30, verbose_name='Número no sistema Sisreg')),
                ('departure_reason', models.CharField(choices=[('A', 'Alta'), ('O', 'Óbito')], default='A', max_length=5, verbose_name='Motivo da Saída')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.Hospital', verbose_name='Hospital')),
            ],
        ),
    ]
