# Generated by Django 3.0 on 2020-04-21 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='departure_reason',
            field=models.CharField(blank=True, choices=[('A', 'Alta'), ('O', 'Óbito')], default='A', max_length=5, verbose_name='Motivo da Saída'),
        ),
        migrations.CreateModel(
            name='PatientBed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed', models.CharField(choices=[('UTIA', 'UTI Adulto'), ('UTIP', 'UTI Pediátrica'), ('UTIN', 'UTI Neonatal'), ('CA', 'Clínico Adulto'), ('CP', 'Clínico Pediátrico'), ('CN', 'Clínico Neonatal'), ('VM', 'Leito Símples com Ventilador Mecânico')], default='UTIA', max_length=38, verbose_name='Tipo do Leito')),
                ('admission_date', models.DateField(verbose_name='Data de Admissão neste Leito')),
                ('waiting_uti', models.BooleanField(default=False, verbose_name='Aguardando UTI')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.Patient', verbose_name='Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalBed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beds', models.CharField(choices=[('UTIA', 'UTI Adulto'), ('UTIP', 'UTI Pediátrica'), ('UTIN', 'UTI Neonatal'), ('CA', 'Clínico Adulto'), ('CP', 'Clínico Pediátrico'), ('CN', 'Clínico Neonatal'), ('VM', 'Leito Símples com Ventilador Mecânico')], default='UTIA', max_length=38, verbose_name='Tipo do Leito')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.Hospital', verbose_name='Hospital')),
            ],
        ),
    ]
