# Generated by Django 3.0.5 on 2020-04-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_hospital_acronym'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalbed',
            name='total',
            field=models.IntegerField(default=0, verbose_name='Total de leitos'),
        ),
        migrations.AddField(
            model_name='hospitalbed',
            name='total_covid',
            field=models.IntegerField(default=0, verbose_name='Total de leitos para Covid-19'),
        ),
    ]
